<div>
    {{-- ═══ Gantt Dark Theme Styles ═══ --}}
    <style>
        .nx-gantt-card {
            background: var(--nx-bg-card, #111118);
            border: 1px solid var(--nx-border, rgba(255,255,255,0.08));
            border-radius: var(--nx-radius-lg, 12px);
            overflow: hidden;
        }
        #gantt-scroll-wrapper {
            overflow-x: auto; overflow-y: hidden; padding: 0;
        }
        #gantt-scroll-wrapper::-webkit-scrollbar { height: 6px; }
        #gantt-scroll-wrapper::-webkit-scrollbar-track { background: transparent; }
        #gantt-scroll-wrapper::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.12); border-radius: 3px; }

        .gantt-container { overflow: visible !important; background: transparent !important; }

        /*
         * KEY FIX: Make grid-background transparent + non-interactive.
         * frappe-gantt renders it ON TOP of bars, so instead of fighting
         * DOM order (which breaks scroll), we just make it see-through.
         */
        .gantt .grid-background { fill: none !important; pointer-events: none !important; }
        .gantt .grid-header { fill: #0a0a12 !important; stroke: none !important; }
        .gantt .grid-row { fill: #0e0e18 !important; }
        .gantt .grid-row:nth-child(even) { fill: #101020 !important; }
        .gantt .row-line { stroke: rgba(255,255,255,0.05) !important; }
        .gantt .tick { stroke: rgba(255,255,255,0.05) !important; }
        .gantt .today-highlight { fill: rgba(59,130,246,0.08) !important; }
        .gantt .holiday-highlight { fill: transparent !important; }
        .gantt .weekend-highlight { fill: transparent !important; }

        /* FIX: Prevent frappe-gantt's sticky header from breaking our scroll wrapper */
        .gantt-container .current-upper { position: static !important; }

        /* FIX: Darken the native 'Today' button generated by frappe-gantt */
        .gantt-container button { 
            background: #111118 !important; 
            color: #e2e8f0 !important; 
            border: 1px solid rgba(255,255,255,0.1) !important; 
            border-radius: 4px;
            padding: 4px 8px;
        }

        .gantt .upper-text { fill: #e2e8f0 !important; font-size: 12px !important; font-weight: 600 !important; font-family: 'Inter', system-ui !important; }
        .gantt .lower-text { fill: #64748b !important; font-size: 10px !important; font-weight: 500 !important; font-family: 'Inter', system-ui !important; }

        .gantt .bar { fill: #3b82f6 !important; rx: 6 !important; ry: 6 !important; filter: drop-shadow(0 2px 8px rgba(59,130,246,0.4)); }
        .gantt .bar-progress { fill: #10b981 !important; rx: 6 !important; ry: 6 !important; }
        .gantt .bar-label { fill: #ffffff !important; font-size: 11px !important; font-weight: 600 !important; font-family: 'Inter', system-ui !important; }
        .gantt .bar-wrapper { cursor: grab !important; }
        .gantt .bar-wrapper:active { cursor: grabbing !important; }
        .gantt .handle { fill: rgba(255,255,255,0.6) !important; cursor: ew-resize !important; opacity: 0; transition: opacity 0.2s; }
        .gantt .bar-wrapper:hover .handle { opacity: 1; }
        .gantt .arrow { stroke: rgba(255,255,255,0.15) !important; stroke-width: 1.5 !important; }

        .gantt-container .popup-wrapper {
            background: #111118 !important; border: 1px solid rgba(255,255,255,0.1) !important;
            border-radius: 10px !important; box-shadow: 0 12px 40px rgba(0,0,0,0.6) !important;
            padding: 12px 16px !important; color: #f0f0f5 !important; font-family: 'Inter', system-ui !important;
        }
        .gantt-container .popup-wrapper .title { font-weight: 600 !important; }
        .gantt-container .popup-wrapper .subtitle { color: #8888a0 !important; }
        .gantt-container .pointer { border-top-color: #111118 !important; }

        /* Zoom buttons */
        .nx-zoom-btn {
            padding: 5px 12px; font-size: 11px; font-weight: 500;
            border: none; cursor: pointer;
            font-family: var(--nx-font-ui, 'Inter', system-ui);
            background: var(--nx-bg-card, #111118);
            color: var(--nx-text-secondary, #8888a0);
            transition: all 0.15s ease;
        }
        .nx-zoom-btn.active {
            background: var(--nx-accent, #10b981);
            color: #fff;
        }
    </style>

    {{-- Header --}}
    <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 24px;">
        <div style="display: flex; align-items: center; gap: 16px;">
            <h2 style="font-size: 18px; font-weight: 700; letter-spacing: -0.02em; margin: 0;">Gantt Şeması</h2>
            <div id="gantt-zoom-controls" style="display: flex; border: 1px solid var(--nx-border); border-radius: var(--nx-radius-md); overflow: hidden;">
                <button class="nx-zoom-btn" onclick="nxGanttZoom('Quarter Day', this)" data-mode="Quarter Day">Çeyrek Gün</button>
                <button class="nx-zoom-btn" onclick="nxGanttZoom('Half Day', this)" data-mode="Half Day">Yarım Gün</button>
                <button class="nx-zoom-btn" onclick="nxGanttZoom('Day', this)" data-mode="Day">Gün</button>
                <button class="nx-zoom-btn active" onclick="nxGanttZoom('Week', this)" data-mode="Week">Hafta</button>
                <button class="nx-zoom-btn" onclick="nxGanttZoom('Month', this)" data-mode="Month">Ay</button>
            </div>
        </div>
        <select wire:model.live="projectId" class="nx-input" style="width: 200px; font-size: 12px; padding: 6px 10px;">
            <option value="">Tüm Projeler</option>
            @foreach($projects as $project)
                <option value="{{ $project->id }}">{{ $project->client_name }}</option>
            @endforeach
        </select>
    </div>

    {{-- Gantt Chart --}}
    <div class="nx-gantt-card">
        @if(empty($ganttData['tasks']))
            <div style="padding: 60px; text-align: center; color: var(--nx-text-muted);">
                <p style="font-size: 14px;">Görevlere başlangıç/bitiş tarihi atayarak Gantt görünümünü kullanabilirsiniz.</p>
            </div>
        @else
            @php
                $mappedTasks = array_map(function($t) {
                    return [
                        'id' => (string) $t['id'],
                        'name' => $t['title'],
                        'start' => $t['start'],
                        'end' => $t['end'],
                        'progress' => $t['status'] === 'done' ? 100 : ($t['status'] === 'in_progress' ? 50 : ($t['status'] === 'review' ? 80 : 0)),
                        'dependencies' => ''
                    ];
                }, $ganttData['tasks']);
            @endphp

            <div id="gantt-scroll-wrapper">
                <div id="gantt-target"></div>
            </div>

            <script>
                // ── Gantt: 100% client-side (no Livewire roundtrip for zoom) ──
                window.__nxGanttDone = false;

                function nxFixColors() {
                    var svg = document.querySelector('.gantt');
                    if (!svg) return;
                    svg.querySelectorAll('rect').forEach(function(r) {
                        var f = (r.getAttribute('fill') || '').toLowerCase().trim();
                        if (['#f5f5f5','#fff','white','#ffffff','#fcfcfc','#fafafa','#f0f0f0',
                             '#e0e0e0','#efefef','#eee','#e8e8e8','#d9d9d9','#ddd'].indexOf(f) !== -1) {
                            r.setAttribute('fill', '#12121e');
                        }
                    });
                }

                function nxGanttZoom(mode, btn) {
                    if (!window.__nxGanttInstance) return;
                    document.querySelectorAll('.nx-zoom-btn').forEach(function(b) { b.classList.remove('active'); });
                    if (btn) btn.classList.add('active');
                    window.__nxGanttInstance.change_view_mode(mode);
                    setTimeout(nxFixColors, 150);
                }

                window.__nxGanttInit = function() {
                    if (window.__nxGanttDone) return;
                    if (typeof window.Gantt === 'undefined') { setTimeout(window.__nxGanttInit, 300); return; }
                    if (!document.getElementById('gantt-target')) return;
                    window.__nxGanttDone = true;

                    var tasks = {!! json_encode($mappedTasks) !!};

                    window.__nxGanttInstance = new window.Gantt("#gantt-target", tasks, {
                        header_height: 50,
                        column_width: 30,
                        step: 24,
                        view_modes: ['Quarter Day', 'Half Day', 'Day', 'Week', 'Month'],
                        bar_height: 24,
                        bar_corner_radius: 6,
                        arrow_curve: 5,
                        padding: 20,
                        view_mode: 'Week',
                        date_format: 'YYYY-MM-DD',
                        language: 'tr'
                    });

                    setTimeout(nxFixColors, 150);

                    // Convert vertical mouse wheel to horizontal scroll (both directions)
                    var wrapper = document.getElementById('gantt-scroll-wrapper');
                    var colorFixTimer = null;
                    if (wrapper) {
                        wrapper.addEventListener('wheel', function(e) {
                            if (Math.abs(e.deltaY) > Math.abs(e.deltaX)) {
                                e.preventDefault();
                                wrapper.scrollLeft += e.deltaY;
                            }
                            // Re-fix colors after frappe-gantt re-renders on scroll
                            clearTimeout(colorFixTimer);
                            colorFixTimer = setTimeout(nxFixColors, 100);
                        }, { passive: false });
                    }
                };

                document.addEventListener('DOMContentLoaded', window.__nxGanttInit);
                document.addEventListener('livewire:initialized', window.__nxGanttInit);
                document.addEventListener('livewire:navigated', window.__nxGanttInit);
                if (document.readyState !== 'loading') {
                    window.__nxGanttInit();
                }
            </script>
        @endif
    </div>
</div>
