<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class PdfGenerationTest extends TestCase
{
    use RefreshDatabase;

    public function test_pdf_library_is_available(): void
    {
        // dompdf or barryvdh/laravel-dompdf should be installed
        $this->assertTrue(
            class_exists(\Barryvdh\DomPDF\Facade\Pdf::class) ||
            class_exists(\Dompdf\Dompdf::class) ||
            class_exists(\Barryvdh\DomPDF\PDF::class),
            'PDF library (dompdf) should be installed'
        );
    }

    public function test_pdf_can_be_generated_from_html(): void
    {
        if (!class_exists(\Barryvdh\DomPDF\Facade\Pdf::class)) {
            $this->markTestSkipped('barryvdh/laravel-dompdf not installed');
        }

        $pdf = \Barryvdh\DomPDF\Facade\Pdf::loadHTML('<h1>Test Report</h1><p>Generated by ADA Co-OS</p>');
        $content = $pdf->output();

        $this->assertNotEmpty($content);
        $this->assertStringStartsWith('%PDF', $content);
    }
}
